services:
  node:
    image: node:22
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    command: >
      sh -c "git config --global user.name 'docker' &&
             git config --global user.email 'docker@example.com' &&
             tail -f /dev/null"
